# Generated by Django 3.2.5 on 2021-12-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autodialer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=20, verbose_name='任务名称')),
                ('start_time', models.DateTimeField(default='', max_length=20, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default='', max_length=20, verbose_name='结束时间')),
                ('cps', models.FloatField(default='', verbose_name='并发')),
                ('predictive_cps', models.FloatField(default='', verbose_name='预测并发')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
            ],
            options={
                'verbose_name': 'Predictive',
                'verbose_name_plural': 'Predictive',
            },
        ),
    ]
