# Generated by Django 3.2.10 on 2022-01-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autodialer', '0003_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': '服务器状态', 'verbose_name_plural': '服务器状态'},
        ),
    ]
