# Generated by Django 3.2.10 on 2022-01-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autodialer', '0004_alter_test_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BroadcastPlayback',
            new_name='Broadcastivr',
        ),
    ]
