# Generated by Django 3.2.10 on 2022-01-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autodialer', '0005_rename_broadcastplayback_broadcastivr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastivr',
            options={'verbose_name': 'Broadcastivr', 'verbose_name_plural': 'Broadcastivr'},
        ),
    ]
