# Generated by Django 3.2.10 on 2022-01-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autodialer', '0006_alter_broadcastivr_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
