# Generated by Django 3.2.10 on 2022-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autodialer', '0008_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now=True, max_length=20, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='describe',
            field=models.FloatField(default='', null=True, verbose_name='描述'),
        ),
    ]
