# Generated by Django 3.2.10 on 2022-01-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autodialer', '0010_auto_20220102_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create_time',
        ),
    ]
