# Generated by Django 3.2.10 on 2022-01-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autodialer', '0011_remove_task_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.CharField(default='', max_length=20, verbose_name='号码'),
        ),
    ]
