# Generated by Django 3.2.10 on 2022-01-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('gateway', models.CharField(default='', max_length=50, verbose_name='网关')),
                ('expression', models.TextField(default='', max_length=20, verbose_name='匹配条件')),
                ('domain', models.CharField(default='', max_length=20, verbose_name='域名')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
            ],
            options={
                'verbose_name': '路由',
                'verbose_name_plural': '路由',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('username', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=20, verbose_name='密码')),
                ('realm', models.CharField(default='', max_length=20, verbose_name='认证地址')),
                ('proxy', models.CharField(default='', max_length=20, verbose_name='认证代理')),
                ('domain', models.CharField(default='', max_length=20, verbose_name='域名')),
                ('register', models.BooleanField(default=False, verbose_name='是否注册')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
            ],
            options={
                'verbose_name': '网关',
                'verbose_name_plural': '网关',
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=20, verbose_name='分机号码')),
                ('password', models.CharField(default='', max_length=20, verbose_name='密码')),
                ('displayname', models.CharField(default='', max_length=20, verbose_name='显示名字')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.domain', verbose_name='域名')),
            ],
            options={
                'verbose_name': '分机',
                'verbose_name_plural': '分机',
            },
        ),
    ]
